#####################################
# Build Signed APKs

signed_production:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    when: on_success
    paths:
      - green/build/outputs/apk/production/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - echo $ANDROID_KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./gradlew assembleProductionRelease

signed_development:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    when: on_success
    paths:
      - green/build/outputs/apk/development/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - echo $ANDROID_KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./gradlew assembleDevelopmentRelease

signed_production_debug:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    when: on_success
    paths:
      - green/build/outputs/apk/production/debug/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - echo $ANDROID_KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./gradlew assembleProductionDebug

#####################################
# Build Unsigned APK

build_google_play:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 hour
    when: on_success
    paths:
      - green/build/outputs/apk/production/release/*.apk
      - green/build/outputs/mapping/*/mapping.txt
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew lintProductionRelease
    - ./gradlew assembleProductionRelease

build_osx:
  stage: build
  when: manual
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew assembleProductionRelease

#####################################
# Test

unit_tests:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: test
  needs: []
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew lintProductionRelease
    - ./gradlew test

#####################################
# Sign production build

sign_google_play:
  tags:
    - garelease
  stage: deploy
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - green/build/outputs/apk/production/release/
    when: on_success
  script: cd $CI_PROJECT_DIR/green/build/outputs/apk && /opt/process_release
  needs:
    - unit_tests
    - build_google_play
