#####################################
# Build Signed APKs

production:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    when: on_success
    paths:
      - green/build/outputs/apk/productionGoogle/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - echo $ANDROID_KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./gradlew assembleProductionGoogleRelease

production_fdroid:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    when: on_success
    paths:
      - green/build/outputs/apk/production/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - echo $ANDROID_KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./gradlew assembleProductionRelease


development:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    when: on_success
    paths:
      - green/build/outputs/apk/development/release/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - echo $ANDROID_KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./gradlew assembleDevelopmentRelease

production_debug:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    when: on_success
    paths:
      - green/build/outputs/apk/productionGoogle/debug/*.apk
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - echo $ANDROID_KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./gradlew assembleProductionGoogleDebug

gdk_commit:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA-gdk-$GDK_COMMIT"
    expire_in: 14 days
    when: on_success
    paths:
      - green/build/outputs/apk/productionGoogle/release/*.apk
  tags:
    - ga
  when: manual
  variables:
    GDK_COMMIT: master
  script:
    - cd $CI_PROJECT_DIR
    - echo $ANDROID_KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./crypto/fetch_gdk_binaries.sh -c $GDK_COMMIT
    - ./gradlew assembleProductionGoogleRelease

#####################################
# Build Unsigned APK

build_google_play:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: build
  when: manual
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 hour
    when: on_success
    paths:
      - green/build/outputs/apk/productionGoogle/release/*.apk
      - green/build/outputs/mapping/*/mapping.txt
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew lintProductionGoogleRelease
    - ./gradlew assembleProductionGoogleRelease

build_osx:
  stage: build
  when: manual
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew assembleProductionGoogleRelease

#####################################
# Test

unit_tests:
  image: greenaddress/android@sha256:1ba279240efe7526185ff344e7b65aa5af4e8eee8e4987a62fc8ee2477de7ff0
  stage: test
  needs: []
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./gradlew lintProductionGoogleRelease
    - ./gradlew test

#####################################
# Sign production build

sign_google_play:
  tags:
    - garelease
  stage: deploy
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - green/build/outputs/apk/productionGoogle/release/
    when: on_success
  script: cd $CI_PROJECT_DIR/green/build/outputs/apk && /opt/process_release
  needs:
    - unit_tests
    - build_google_play
