language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      before_install:
        - docker pull greenaddress/android@sha256:2c5add76a59357d84775ad188ea2c00d57838ac5a3e4a046e779a296aad39924
      script: docker run -v $PWD:/gb greenaddress/android /bin/sh -c "cd /gb/app && ./prepare_fdroid.sh && cd /gb && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew assembleProductionRelease"
    - services:
        - docker
      before_install:
        - docker pull greenaddress/android@sha256:2c5add76a59357d84775ad188ea2c00d57838ac5a3e4a046e779a296aad39924
      script: docker run -v $PWD:/gb greenaddress/android /bin/sh -c "cd /gb/app && ./prepare_fdroid.sh && cd /gb && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew assembleBtctestnetRelease"
    - services:
        - docker
      before_install:
        - docker pull greenaddress/android@sha256:2c5add76a59357d84775ad188ea2c00d57838ac5a3e4a046e779a296aad39924
      script: docker run -v $PWD:/gb greenaddress/android /bin/sh -c "cd /gb/app && ./prepare_fdroid.sh && cd /gb && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew assembleElementsregtestRelease"
    - os: osx
      osx_image: xcode8.3
      env:
        - ANDROID_NDK=/Users/travis/opt/android-ndk-r14b
        - ANDROID_HOME=/Users/travis/opt
        - SDK_FILENAME=sdk-tools-darwin-3859397.zip
        - NDK_FILENAME=android-ndk-r14b-darwin-x86_64.zip
      before_install: rm -rf /home/travis/.nvm
      install:
        - mkdir -p $HOME/opt/licenses
        - cd $HOME/opt && curl -sSO https://dl.google.com/android/repository/${SDK_FILENAME} && unzip -qq ${SDK_FILENAME}
        - cd $HOME/opt && curl -sSO https://dl.google.com/android/repository/${NDK_FILENAME} && unzip -qq ${NDK_FILENAME}
        - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $HOME/opt/licenses/android-sdk-license
        - brew update
        - brew upgrade
        - brew install swig coreutils gnu-sed automake autoconf pkg-config
        - $HOME/opt/tools/bin/sdkmanager "tools" "platform-tools"
        - $HOME/opt/tools/bin/sdkmanager "build-tools;25.0.3"
        - $HOME/opt/tools/bin/sdkmanager "platforms;android-25"
        - $HOME/opt/tools/bin/sdkmanager "extras;android;m2repository" "extras;google;m2repository"
      script:
        - export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
        - cd $HOME/build/greenaddress/GreenBits/app && ./prepare_fdroid.sh
        - cd $HOME/build/greenaddress/GreenBits && ./gradlew assembleProductionDebug
