language: android
sudo: required
android:
    components:
        - tools
        - build-tools-23.0.3
        - android-23
        - platform-tools-23
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - '.+'

jdk:
    - oraclejdk7

script:
   - sed -i -e 's/enable true/enable false/g' app/build.gradle
   - ./gradlew --stacktrace clean assembleProductRelease -PdisablePreDex

before_install:
   - curl -O http://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
   - unzip -qq ./android-ndk-r12b-linux-x86_64.zip
   - export ANDROID_NDK=`pwd`/android-ndk-r12b
   - rm -fr app/src/main/jniLibs && pushd app && ./prepare_fdroid.sh && popd
   - find app/src/main/jniLibs | xargs ls -laht

addons:
    apt:
        packages:
           - swig
