language: android
sudo: required
android:
    components:
        - tools
        - build-tools-23.0.3
        - android-23
        - platform-tools-23
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - '.+'

jdk:
    - oraclejdk7

script:
   - ./gradlew clean assembleProductRelease assembleProduction_21Release -PdisablePreDex

before_install:
   - git submodule update --init --recursive
   - curl -O http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip
   - unzip -qq ./android-ndk-r11c-linux-x86_64.zip
   - export ANDROID_NDK=`pwd`/android-ndk-r11c
   - rm -fr app/src/main/jniLibs && pushd app && ./prepare_fdroid.sh && popd
